### ISSUE TITLE
Websocket guide for adonisjs 5

### ISSUE THREAD

**Issue by soonzhi** [adonisjs/v5-docs#49]
Hi bros,
Just to quick check with you guys whether have guides to setup websocket with Adonisjs using ws library instead of socket.io
I saw this:
https://docs.adonisjs.com/cookbooks/socketio-with-adonisjs

Hope to get some guide on integrate with ws

**Comment by RomainLanz** [comment]
Hey @soonzhi! 👋 

We do not have any guide that shows how to use `ws` instead of `socket.io`. However, it should not be that different.

Also, this is more a question than an issue with the framework itself.
Since we want to keep this space clean, please use [GitHub Discussion](https://github.com/adonisjs/core/discussions) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
